name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Readme Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: Zapotichnyi06
